export const ERROR_MESSAGES = {
  AUTH: {
    INVALID_PHONE_FORMAT: 'Formato de teléfono inválido. Debe contener 10 dígitos.',
    CONNECTION_ERROR: 'Error de conexión al buscar cliente. Inténtalo de nuevo.',
    INVALID_CREDENTIALS: 'PIN incorrecto. Inténtalo de nuevo.',
    PIN_VERIFICATION_FAILED: 'Error al verificar el PIN.',
    CLIENT_NOT_FOUND: 'No encontramos una cuenta con este número de teléfono.',
    PIN_REGISTER_ERROR: 'Error al registrar tu PIN. Inténtalo de nuevo.',
  },
  VALIDATION: {
    REQUIRED_FIELDS: 'Completa todos los campos.',
    INVALID_PIN_LENGTH: 'El PIN debe tener 4 dígitos.',
  },
  DB: {
    GENERIC_ERROR: 'Ocurrió un error inesperado.',
  },
  CLIENTS: {
    LOAD_ERROR: 'No se pudieron cargar los clientes.',
    NAME_REQUIRED: 'El nombre es requerido y debe tener al menos 3 caracteres.',
    PHONE_REQUIRED: 'El teléfono es requerido y debe tener 10 dígitos.',
    PHONE_EXISTS: 'El número de teléfono ya está registrado.',
    CREATE_PERMISSION_DENIED: 'No tienes permiso para crear o actualizar clientes.',
    SAVE_ERROR: 'Error al guardar el cliente.',
    POINTS_INVALID: 'La cantidad de puntos debe ser un número.',
    CONCEPT_REQUIRED: 'El concepto es requerido.',
    ASSIGN_POINTS_ERROR: 'Error al asignar puntos.',
    HISTORY_ERROR: 'Ocurrió un error al buscar tu historial.',
    NOT_FOUND: 'Cliente no encontrado.',
    LOAD_REDEMPTIONS_ERROR: 'Error al cargar canjes del cliente.',
    LOAD_POINTS_ERROR: 'Error al cargar historial de puntos.',
    LOAD_SERVICES_ERROR: 'Error al cargar servicios asignados.',
    LOAD_HISTORY_SERVICES_ERROR: 'Error al cargar historial de servicios.',
    LEVEL_INVALID: 'El nivel debe ser partner o vip.',
    LEVEL_CHANGE_ERROR: 'Error al cambiar el nivel del cliente.',
    ROLE_CHANGE_ERROR: 'Error al cambiar el rol del usuario.',
  },
  PRODUCTS: {
    LOAD_ERROR: 'No se pudieron cargar los productos.',
    LOAD_REDEMPTION_ERROR: 'No se pudieron cargar los productos para canje.',
    NOT_FOUND: 'Error al buscar el producto.',
    NAME_REQUIRED: 'El nombre del producto es requerido.',
    POINTS_INVALID: 'Los puntos deben ser un número mayor a cero.',
    CREATE_PERMISSION_DENIED: 'No tienes permiso para crear o actualizar productos.',
    SAVE_ERROR: 'Error al guardar el producto.',
    DELETE_ERROR: 'Error al eliminar el producto.',
  },
  REDEMPTIONS: {
    LOAD_ERROR: 'No se pudieron cargar los canjes.',
    LOAD_PENDING_ERROR: 'No se pudieron cargar los canjes pendientes.',
    UPDATE_STATUS_ERROR: 'Error al actualizar el estado del canje.',
    INSUFFICIENT_POINTS: 'No tienes suficientes puntos para este canje.',
    OUT_OF_STOCK: 'Lo sentimos, este producto está agotado.',
    PROCESS_ERROR: 'No se pudo procesar el canje en este momento.',
  },
  SERVICES: {
    LOAD_ERROR: 'Error al cargar tus servicios.',
    REDEEM_ERROR: 'Error al canjear el servicio.',
    CREATE_ERROR: 'Error al asignar el servicio.',
    DELETE_ERROR: 'Error al eliminar el servicio.',
    HISTORY_ERROR: 'Error al cargar el historial de servicios.',
    STATS_ERROR: 'Error al cargar estadísticas.',
  },
  ADMIN: {
    EXPORT_CLIENTS_ERROR: 'Error exportando clientes',
    EXPORT_PRODUCTS_ERROR: 'Error exportando productos',
    EXPORT_REDEMPTIONS_ERROR: 'Error exportando canjes',
    EXPORT_HISTORY_ERROR: 'Error exportando historial',
    IMPORT_FORMAT_ERROR: 'El archivo no tiene el formato correcto.',
    IMPORT_CLIENTS_ERROR: 'Error importando clientes',
    IMPORT_PRODUCTS_ERROR: 'Error importando productos',
    REMINDERS_LOAD_ERROR: 'Error al cargar configuración de recordatorios.',
    REMINDERS_UPDATE_ERROR: 'Error al actualizar configuración.',
    REMINDERS_CREATE_ERROR: 'Error al crear configuración.',
    SERVICE_TYPES_LOAD_ERROR: 'Error al cargar tipos de servicio recurrente.',
    SERVICE_TYPES_UPDATE_ERROR: 'Error al actualizar tipo de servicio.',
    SERVICE_TYPES_ADD_ERROR: 'Error al agregar tipo de servicio.',
    SERVICE_TYPES_DUPLICATE: 'Este tipo de servicio ya existe.',
    SERVICE_TYPES_DELETE_ERROR: 'Error al eliminar tipo de servicio.',
  },
  GIFTS: {
    LOAD_ERROR: 'Error al cargar links de regalo',
    CLAIM_ERROR: 'Error al canjear el regalo. Intenta de nuevo.',
    INVALID_CODE: 'Código de regalo inválido',
    INVALID_PHONE: 'Número de teléfono inválido (10 dígitos)',
    BENEFITS_LOAD_ERROR: 'Error al cargar tus beneficios',
    CREATE_ERROR: 'Error al crear el link de regalo',
    STATS_ERROR: 'Error al cargar estadísticas',
    BENEFICIARIES_ERROR: 'Error al cargar beneficiarios',
    MARK_USED_ERROR: 'Error al marcar beneficio como usado',
    EXPIRE_ERROR: 'Error al expirar el link',
    DELETE_ERROR: 'Error al eliminar el link',
    DELETE_HAS_BENEFICIARIES: 'No se puede eliminar un link que ya tiene beneficiarios',
    TICKET_ERROR: 'Error al crear ticket para el beneficio',
  },
  REFERRALS: {
    CODE_ERROR: 'Error al obtener tu código de referido',
    LOAD_ERROR: 'Error al cargar tus referidos',
    INVALID_CODE: 'Código de referido inválido',
    APPLY_ERROR: 'Error al aplicar el código de referido',
    CONFIG_LOAD_ERROR: 'Error al cargar configuración',
    STATS_ERROR: 'Error cargando estadísticas',
    ALL_LOAD_ERROR: 'Error al cargar referidos',
    CONFIG_SAVE_ERROR: 'Error al guardar configuración',
  }
};
